### ISSUE TITLE
SEC_ERROR_REUSED_ISSUER_AND_SERIAL if you install more than one instance

### ISSUE THREAD

**Issue by sargolin** [Joe-Klauza/sandstorm-admin-wrapper#109]
In case you install more than one instance on different servers, Firefox produces an error because the SSL certificate stays the same and can't be used more than once. The different hostnames but same SSL serials produce an error. Perhaps you can provide fresh certificates during install routine with CertBot or alike.

Thanks,
Oliver

**Comment by sargolin** [comment]
Problem solved by using certbot to create new certificates and drop them in the config folder and in the config. All good now.

**Comment by Joe-Klauza** [comment]
Thanks for the report and the resolution, @sargolin. I was aware Firefox gives developers less freedom with self-signed SSL certificates in order to improve user security, so I had not been testing much with it. One example where I had trouble in the past was that regenerating the certificate would prevent access to SAW entirely through Firefox if both were self-signed (likely attempted MITM mitigation by the browser).

Using certbot was a good solution. 👍
