### ISSUE TITLE
Failed to encode string as UTF-8

### ISSUE THREAD

**Issue by kawon7317** [Joe-Klauza/sandstorm-admin-wrapper#116]
| WARN    | Failed to encode string as UTF-8: "\xE9\x92\x89\xE5\xAE\xABMQ"
| WARN    | Failed to encode string as UTF-8: "\xE7\xA5\x9E\xE7\xBB\x8F\xE6\xB6\x9B"
| WARN    | Failed to encode string as UTF-8: "\xE9\xA9\xAC\xE5\x8B\x92\xE6\xA0\xBC\xE5\xBD\xBC\xE5\xBE\x97"
| WARN    | Failed to encode string as UTF-8: "\xE9\x92\x89\xE5\xAE\xABMQ"
| WARN    | Failed to encode string as UTF-8: "\xE7\xA5\x9E\xE7\xBB\x8F\xE6\xB6\x9B"
| WARN    | Failed to encode string as UTF-8: "\xE9\xA9\xAC\xE5\x8B\x92\xE6\xA0\xBC\xE5\xBD\xBC\xE5\xBE\x97"

**Comment by Joe-Klauza** [comment]
Hi, @kawon7317! This is unfortunately a common problem. AFAIK [RCON](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol) was not designed for UTF characters, and sometimes there are issues with the response or parsing when East Asian Width characters or other special characters are present (e.g. in usernames). I don't know if there is anything I can do to solve this; it would take a deep dive into the RCON client and server interactions, which are already an absolute mess in order to support this game's RCON server implementation.

**Comment by kawon7317** [comment]
i got it. thank you for your prompt reply
