### ISSUE TITLE
Server query Failed

### ISSUE THREAD

**Issue by jbuitt** [Joe-Klauza/sandstorm-admin-wrapper#140]
Hello! 

Amazing software! I just installed on a new DigitalOcean Ubuntu 22.04 server. Got all the prerequisites installed and created a config. However, when I start it up, I start receiving the following error shortly after:

```
2023-09-16 19:23:19 +0000 | ERROR   | 127.0.0.1:[27131,27015] Monitor | Server query failed | Exception occurred (NoUDPResponseError): Could not read a UDP response from server 127.0.0.1:27131
```

Since it can't successfully query the server, it keeps restarting it in a endless loop, which I assume is expected. Is there something I might have missed that would cause the query to fail? The firewall is open so no ports are being blocked. I have also tried the instructions for installing on server and Docker, both result in same above error.

Thanks!

Jim

**Comment by Joe-Klauza** [comment]
Hi @jbuitt. The most likely reason server query is failing is because something else has bound the expected port (27131), which can be checked with a command like `netstat -tlupn` to see which ports are bound to which processes. 

If nothing is listening on the port, I would recommend inspecting the server logs to see why it is failing to start the server query listener. Perhaps if you are using a [Steam Game Server Login Token](https://steamcommunity.com/dev/managegameservers) that is expired it could cause this issue.

**Comment by jbuitt** [comment]
Hey @Joe-Klauza !

Yup, the Server Login Token was wrong. I created a new one and now all is well.

Thanks for the help! I'll go ahead and close this issue.

Jim
