### ISSUE TITLE
ipaddr and bundler problem

### ISSUE THREAD

**Issue by alphatonic** [Joe-Klauza/sandstorm-admin-wrapper#74]
Bundling
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Your bundle is locked to ipaddr (1.2.2), but that version could not be found in
any of the sources listed in your Gemfile. If you haven't changed sources, that
means the author of ipaddr (1.2.2) has removed it. You'll need to update your
bundle to a version other than ipaddr (1.2.2) that hasn't been removed in order
to install.
Failed to run Ruby Bundler. Ensure Ruby is installed with the bundler gem. https://rubyinstaller.org/downloads/

Everything should be up to date.

**Comment by Joe-Klauza** [comment]
Hey, @alphatonic! Glad you were able to resolve it. If this happens again (or to anyone else), I recommend `gem uninstall ipaddr --version 1.2.2` (or whatever version is causing the error). I imagine this gem version was being used in your Ruby environment by another project, and since my `openssl` dependency doesn't call for a specific version of its `ipaddr` dependency, it was trying to use the known/removed version.
